# Generated by Django 4.2.19 on 2025-03-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(max_length=100, verbose_name='Nom du fournisseur')),
                ('type_fournisseur', models.CharField(choices=[('Carburant', 'Carburant'), ('Maintenance', 'Maintenance'), ('Assurance', 'Assurance')], max_length=20, verbose_name='Type de fournisseur')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('chassis', models.CharField(max_length=100, unique=True, verbose_name='Numéro de châssis')),
                ('immatriculation', models.CharField(max_length=50, unique=True, verbose_name='Immatriculation')),
                ('type_carburant', models.CharField(choices=[('Essence', 'Essence'), ('Gasoil', 'Gasoil')], max_length=10, verbose_name='Type de carburant')),
                ('date_mise_en_service', models.DateField(verbose_name='Date de mise en service')),
                ('kilometrage', models.PositiveIntegerField(verbose_name='Kilométrage')),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Non Disponible', 'Non Disponible')], default='Disponible', max_length=15, verbose_name='Statut')),
                ('document', models.FileField(blank=True, null=True, upload_to='vehicules/documents/', verbose_name='Document')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/photos/', verbose_name='Photo')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='Carte_Carburant',
            fields=[
                ('id_carte_carburant', models.AutoField(primary_key=True, serialize=False)),
                ('numero_carte', models.CharField(max_length=100, unique=True, verbose_name='Numéro de carte')),
                ('solde', models.PositiveIntegerField(default=0, verbose_name='Solde (XOF)')),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Non Disponible', 'Non Disponible')], default='Disponible', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_carburant', to='core.service', verbose_name='Service')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_carburant', to='core.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Carte carburant',
                'verbose_name_plural': 'Cartes carburant',
            },
        ),
        migrations.CreateModel(
            name='Achat_Stock_Carburant_HT',
            fields=[
                ('id_achat_stock_carburant_ht', models.AutoField(primary_key=True, serialize=False)),
                ('voucher', models.CharField(max_length=100, verbose_name='Numéro de voucher')),
                ('business_unit', models.CharField(max_length=100, verbose_name='Business Unit')),
                ('dept_id', models.CharField(max_length=100, verbose_name='Département ID')),
                ('project_id', models.CharField(max_length=100, verbose_name='Projet ID')),
                ('date_achat', models.DateField(verbose_name="Date d'achat")),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('type_carburant', models.CharField(choices=[('Essence', 'Essence'), ('Gasoil', 'Gasoil')], max_length=10, verbose_name='Type de carburant')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (litres)')),
                ('montant_ht', models.PositiveIntegerField(verbose_name='Montant HT (XOF)')),
                ('montant_ttc', models.PositiveIntegerField(verbose_name='Montant TTC (XOF)')),
                ('document', models.FileField(blank=True, null=True, upload_to='achats/documents/', verbose_name='Document')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_stock_carburant_ht', to='core.fournisseur', verbose_name='Fournisseur')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_stock_carburant_ht', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Achat stock carburant HT',
                'verbose_name_plural': 'Achats stock carburant HT',
            },
        ),
        migrations.CreateModel(
            name='Achat_Carburant_TTC',
            fields=[
                ('id_achat_carburant_ttc', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('voucher', models.CharField(max_length=100, verbose_name='Numéro de voucher')),
                ('business_unit', models.CharField(max_length=100, verbose_name='Business Unit')),
                ('dept_id', models.CharField(max_length=100, verbose_name='Département ID')),
                ('project_id', models.CharField(max_length=100, verbose_name='Projet ID')),
                ('date_achat', models.DateField(verbose_name="Date d'achat")),
                ('type_carburant', models.CharField(choices=[('Essence', 'Essence'), ('Gasoil', 'Gasoil')], max_length=10, verbose_name='Type de carburant')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (litres)')),
                ('montant_ttc', models.PositiveIntegerField(verbose_name='Montant TTC (XOF)')),
                ('document', models.FileField(blank=True, null=True, upload_to='achats/documents/', verbose_name='Document')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_carburant_ttc', to='core.carte_carburant', verbose_name='Carte carburant')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_carburant_ttc', to='core.fournisseur', verbose_name='Fournisseur')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_carburant_ttc', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Achat carburant TTC',
                'verbose_name_plural': 'Achats carburant TTC',
            },
        ),
    ]
