# Generated by Django 4.2.19 on 2025-03-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fournisseur_vehicule_carte_carburant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
