# Generated by Django 4.2.19 on 2025-03-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groupe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechargement_Carte_Carburant',
            fields=[
                ('id_rechargement', models.AutoField(primary_key=True, serialize=False)),
                ('date_rechargement', models.DateField(verbose_name='Date de rechargement')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (litres)')),
                ('montant_ttc', models.PositiveIntegerField(verbose_name='Montant TTC (XOF)')),
                ('achat_stock_carburant_ht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechargements', to='core.achat_stock_carburant_ht', verbose_name='Achat stock carburant HT')),
                ('carte_carburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechargements', to='core.carte_carburant', verbose_name='Carte carburant')),
            ],
            options={
                'verbose_name': 'Rechargement carte carburant',
                'verbose_name_plural': 'Rechargements cartes carburant',
            },
        ),
    ]
