# Generated by Django 4.2.19 on 2025-03-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rechargement_carte_carburant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rechargement_carte_carburant',
            options={'verbose_name': 'Rechargement de carte carburant', 'verbose_name_plural': 'Rechargements de cartes carburant'},
        ),
        migrations.AlterUniqueTogether(
            name='rechargement_carte_carburant',
            unique_together={('achat_stock_carburant_ht', 'carte_carburant')},
        ),
    ]
