# Generated by Django 4.2.19 on 2025-03-15 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rechargement_carte_carburant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande_Carte_Carburant',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('motif_demande', models.TextField(verbose_name='Motif de la demande')),
                ('statut_demande', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Rejetée', 'Rejetée'), ('Close', 'Close')], default='En attente', max_length=20, verbose_name='Statut de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('ancien_solde_carte', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancien solde de la carte (XOF)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_ravitaillement', models.DateField(blank=True, null=True, verbose_name='Date de ravitaillement')),
                ('km_vehicule', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage du véhicule')),
                ('prix_unitaire_ttc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix unitaire TTC (XOF)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume (litres)')),
                ('montant_ttc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Montant TTC (XOF)')),
                ('nouveau_solde_carte', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nouveau solde de la carte (XOF)')),
                ('document', models.FileField(blank=True, null=True, upload_to='demandes/documents/', verbose_name='Document justificatif')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('carte_carburant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='core.carte_carburant', verbose_name='Carte carburant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_carte_carburant', to='core.service', verbose_name='Service')),
                ('utilisateur_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_initiees', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur demandeur')),
                ('utilisateur_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire traitant')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_carte_carburant', to='core.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Demande de carte carburant',
                'verbose_name_plural': 'Demandes de cartes carburant',
            },
        ),
    ]
