# Generated by Django 4.2.19 on 2025-03-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_demande_carte_carburant'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='fiche_ravitaillement',
            field=models.FileField(blank=True, null=True, upload_to='fiches_ravitaillement/', verbose_name='Fiche de ravitaillement'),
        ),
    ]
