# Generated by Django 4.2.19 on 2025-03-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_demande_carte_carburant_fiche_ravitaillement'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom complet'),
        ),
    ]
