# Generated by Django 4.2.19 on 2025-03-16 17:44

from django.db import migrations, models


def combine_names(apps, schema_editor):
    # Récupérer le modèle Utilisateur historique
    Utilisateur = apps.get_model('core', 'Utilisateur')
    # Mettre à jour tous les utilisateurs existants
    for user in Utilisateur.objects.all():
        user.nom_complet = f"{user.prenom} {user.nom}"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_utilisateur_nom_complet'),
    ]

    operations = [
        # Première étape : s'assurer que le champ nom_complet n'est plus vide
        migrations.RunPython(combine_names),
        
        # Deuxième étape : supprimer les champs devenus inutiles
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom_complet',
            field=models.CharField(max_length=200, verbose_name='Nom complet'),
        ),
    ]
