# Generated by Django 4.2.19 on 2025-03-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_username_merge_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat_carburant_ttc',
            name='carte',
        ),
    ]
