# Generated by Django 4.2.19 on 2025-03-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_achat_carburant_ttc_carte'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rechargement_carte_carburant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rechargement_carte_carburant',
            name='achat_carburant_ttc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechargements', to='core.achat_carburant_ttc', verbose_name='Achat carburant TTC'),
        ),
        migrations.AlterField(
            model_name='rechargement_carte_carburant',
            name='achat_stock_carburant_ht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechargements', to='core.achat_stock_carburant_ht', verbose_name='Achat stock carburant HT'),
        ),
        migrations.AddConstraint(
            model_name='rechargement_carte_carburant',
            constraint=models.CheckConstraint(check=models.Q(('achat_stock_carburant_ht__isnull', False), ('achat_carburant_ttc__isnull', False), _connector='OR'), name='one_achat_type_required'),
        ),
        migrations.AddConstraint(
            model_name='rechargement_carte_carburant',
            constraint=models.UniqueConstraint(condition=models.Q(('achat_stock_carburant_ht__isnull', False)), fields=('achat_stock_carburant_ht', 'carte_carburant'), name='unique_ht_carte'),
        ),
        migrations.AddConstraint(
            model_name='rechargement_carte_carburant',
            constraint=models.UniqueConstraint(condition=models.Q(('achat_carburant_ttc__isnull', False)), fields=('achat_carburant_ttc', 'carte_carburant'), name='unique_ttc_carte'),
        ),
    ]
