# Generated by Django 4.2.19 on 2025-03-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_rechargement_carte_carburant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=255, verbose_name="Sujet de l'email")),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('contenu', models.TextField(verbose_name="Contenu de l'email")),
                ('statut', models.CharField(max_length=20, verbose_name="Statut de l'envoi")),
                ('date_envoi', models.DateTimeField(verbose_name="Date d'envoi")),
                ('erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': "Log d'email",
                'verbose_name_plural': "Logs d'emails",
            },
        ),
    ]
