# Generated by Django 4.2.19 on 2025-03-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_carte_carburant',
            name='statut_demande',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Rejetée', 'Rejetée'), ('Close', 'Clôturée')], default='En attente', max_length=20, verbose_name='Statut de la demande'),
        ),
    ]
