# Generated by Django 4.2.19 on 2025-03-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_demande_carte_carburant_statut_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='station_service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Station service'),
        ),
    ]
