# Generated by Django 4.2.19 on 2025-03-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_demande_carte_carburant_station_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='dotation_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la dotation'),
        ),
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='dotation_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source de dotation'),
        ),
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='dotation_type',
            field=models.CharField(blank=True, choices=[('HT', 'Achat HT'), ('TTC', 'Achat TTC')], max_length=10, null=True, verbose_name='Type de dotation'),
        ),
    ]
