# Generated by Django 4.2.19 on 2025-03-22 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_demande_carte_carburant_dotation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat_carburant_ttc',
            name='statut',
            field=models.CharField(choices=[('Ouverte', 'Ouverte'), ('Close', 'Close')], default='Ouverte', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='achat_stock_carburant_ht',
            name='statut',
            field=models.CharField(choices=[('Ouverte', 'Ouverte'), ('Close', 'Close')], default='Ouverte', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='carte_carburant',
            name='dotation_active_ht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_actives', to='core.achat_stock_carburant_ht', verbose_name='Dotation HT active'),
        ),
        migrations.AddField(
            model_name='carte_carburant',
            name='dotation_active_ttc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_actives', to='core.achat_carburant_ttc', verbose_name='Dotation TTC active'),
        ),
        migrations.AddConstraint(
            model_name='carte_carburant',
            constraint=models.CheckConstraint(check=models.Q(('dotation_active_ht__isnull', True), ('dotation_active_ttc__isnull', True), _connector='OR'), name='one_dotation_active_at_a_time'),
        ),
    ]
