# Generated by Django 4.2.19 on 2025-03-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_achat_carburant_ttc_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat_carburant_ttc',
            name='montant_ttc',
            field=models.PositiveIntegerField(verbose_name='Montant TTC (FCFA)'),
        ),
        migrations.AlterField(
            model_name='achat_stock_carburant_ht',
            name='montant_ht',
            field=models.PositiveIntegerField(verbose_name='Montant HT (FCFA)'),
        ),
        migrations.AlterField(
            model_name='achat_stock_carburant_ht',
            name='montant_ttc',
            field=models.PositiveIntegerField(verbose_name='Montant TTC (FCFA)'),
        ),
        migrations.AlterField(
            model_name='carte_carburant',
            name='numero_carte',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de carte'),
        ),
        migrations.AlterField(
            model_name='carte_carburant',
            name='solde',
            field=models.PositiveIntegerField(default=0, verbose_name='Solde (FCFA)'),
        ),
        migrations.AlterField(
            model_name='carte_carburant',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Attribué', 'Attribué'), ('Non disponible', 'Non disponible')], default='Disponible', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='demande_carte_carburant',
            name='ancien_solde_carte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancien solde de la carte (FCFA)'),
        ),
        migrations.AlterField(
            model_name='demande_carte_carburant',
            name='montant_ttc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Montant TTC (FCFA)'),
        ),
        migrations.AlterField(
            model_name='demande_carte_carburant',
            name='nouveau_solde_carte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nouveau solde de la carte (FCFA)'),
        ),
        migrations.AlterField(
            model_name='demande_carte_carburant',
            name='prix_unitaire_ttc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix unitaire TTC (FCFA)'),
        ),
        migrations.AlterField(
            model_name='rechargement_carte_carburant',
            name='montant_ttc',
            field=models.PositiveIntegerField(verbose_name='Montant TTC (FCFA)'),
        ),
    ]
