# Generated by Django 4.2.19 on 2025-03-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_achat_carburant_ttc_montant_ttc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechargement_Carte_Carburant_HT',
            fields=[
                ('id_rechargement_ht', models.AutoField(primary_key=True, serialize=False)),
                ('date_rechargement', models.DateField(verbose_name='Date de rechargement')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (litres)')),
                ('prix_unitaire_ttc', models.PositiveIntegerField(verbose_name='Prix unitaire TTC (FCFA)')),
                ('montant_ttc', models.PositiveIntegerField(verbose_name='Montant TTC (FCFA)')),
                ('achat_stock_carburant_ht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechargements_ht', to='core.achat_stock_carburant_ht', verbose_name='Achat stock carburant HT')),
                ('carte_carburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechargements_ht', to='core.carte_carburant', verbose_name='Carte carburant')),
            ],
            options={
                'verbose_name': 'Rechargement de carte carburant HT',
                'verbose_name_plural': 'Rechargements de cartes carburant HT',
            },
        ),
        migrations.CreateModel(
            name='Rechargement_Carte_Carburant_TTC',
            fields=[
                ('id_rechargement_ttc', models.AutoField(primary_key=True, serialize=False)),
                ('date_rechargement', models.DateField(verbose_name='Date de rechargement')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (litres)')),
                ('prix_unitaire_ttc', models.PositiveIntegerField(verbose_name='Prix unitaire TTC (FCFA)')),
                ('montant_ttc', models.PositiveIntegerField(verbose_name='Montant TTC (FCFA)')),
                ('achat_carburant_ttc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechargements_ttc', to='core.achat_carburant_ttc', verbose_name='Achat carburant TTC')),
                ('carte_carburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechargements_ttc', to='core.carte_carburant', verbose_name='Carte carburant')),
            ],
            options={
                'verbose_name': 'Rechargement de carte carburant TTC',
                'verbose_name_plural': 'Rechargements de cartes carburant TTC',
            },
        ),
        migrations.DeleteModel(
            name='Rechargement_Carte_Carburant',
        ),
        migrations.AddConstraint(
            model_name='rechargement_carte_carburant_ttc',
            constraint=models.UniqueConstraint(fields=('achat_carburant_ttc', 'carte_carburant'), name='unique_ttc_carte_rechargement'),
        ),
        migrations.AddConstraint(
            model_name='rechargement_carte_carburant_ht',
            constraint=models.UniqueConstraint(fields=('achat_stock_carburant_ht', 'carte_carburant'), name='unique_ht_carte_rechargement'),
        ),
    ]
