# Generated by Django 4.2.19 on 2025-03-22 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rechargement_carte_carburant_ht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_carte_carburant',
            name='ancien_solde_carte',
        ),
        migrations.RemoveField(
            model_name='demande_carte_carburant',
            name='carte_carburant',
        ),
        migrations.RemoveField(
            model_name='demande_carte_carburant',
            name='dotation_id',
        ),
        migrations.RemoveField(
            model_name='demande_carte_carburant',
            name='dotation_source',
        ),
        migrations.RemoveField(
            model_name='demande_carte_carburant',
            name='dotation_type',
        ),
        migrations.RemoveField(
            model_name='demande_carte_carburant',
            name='nouveau_solde_carte',
        ),
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='rechargement_ht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='core.rechargement_carte_carburant_ht', verbose_name='Rechargement HT'),
        ),
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='rechargement_ttc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='core.rechargement_carte_carburant_ttc', verbose_name='Rechargement TTC'),
        ),
        migrations.AddField(
            model_name='rechargement_carte_carburant_ht',
            name='solde_restant',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Solde restant'),
        ),
        migrations.AddField(
            model_name='rechargement_carte_carburant_ttc',
            name='solde_restant',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Solde restant'),
        ),
    ]
