# Generated by Django 4.2.19 on 2025-03-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_demande_carte_carburant_ancien_solde_carte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargement_carte_carburant_ht',
            name='volume_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume restant (litres)'),
        ),
        migrations.AddField(
            model_name='rechargement_carte_carburant_ttc',
            name='volume_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume restant (litres)'),
        ),
    ]
