# Generated by Django 4.2.19 on 2025-03-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rechargement_carte_carburant_ht_volume_restant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='ancien_solde_carte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancien solde de la carte'),
        ),
        migrations.AddField(
            model_name='demande_carte_carburant',
            name='nouveau_solde_carte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nouveau solde de la carte'),
        ),
    ]
