# Generated by Django 4.2.19 on 2025-04-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_demande_carte_carburant_ancien_solde_carte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Type de maintenance',
                'verbose_name_plural': 'Types de maintenance',
            },
        ),
        migrations.AlterModelOptions(
            name='demande_carte_carburant',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Demande de carte carburant', 'verbose_name_plural': 'Demandes de cartes carburant'},
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField(verbose_name='Détail de la maintenance')),
                ('date', models.DateField(verbose_name='Date de maintenance')),
                ('km_vehicule', models.PositiveIntegerField(verbose_name='Kilométrage après intervention')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('periodicite_km', models.PositiveIntegerField(blank=True, help_text='Kilométrage avant la prochaine maintenance de ce type', null=True, verbose_name='Périodicité kilométrique')),
                ('alerte_km', models.PositiveIntegerField(blank=True, help_text="Marge d'alerte en kilomètres avant l'échéance", null=True, verbose_name="Marge d'alerte kilométrique")),
                ('periodicite_mois', models.PositiveIntegerField(blank=True, help_text='Nombre de mois avant la prochaine maintenance de ce type', null=True, verbose_name='Périodicité en mois')),
                ('alerte_mois', models.PositiveIntegerField(blank=True, help_text="Marge d'alerte en mois avant l'échéance", null=True, verbose_name="Marge d'alerte en mois")),
                ('facture', models.FileField(help_text='Document obligatoire', upload_to='factures_maintenance/', verbose_name='Facture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('fournisseur', models.ForeignKey(limit_choices_to={'type_fournisseur': 'Maintenance'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.fournisseur', verbose_name='Fournisseur')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.service', verbose_name='Service')),
                ('type_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.typemaintenance', verbose_name='Type de maintenance')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date'],
            },
        ),
    ]
