# Generated by Django 4.2.19 on 2025-04-11 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_typemaintenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prochaine_echeance_km', models.PositiveIntegerField(help_text='Kilométrage auquel la prochaine maintenance doit être effectuée', verbose_name='Prochaine échéance kilométrique')),
                ('prochaine_echeance_date', models.DateField(blank=True, help_text='Date à laquelle la prochaine maintenance doit être effectuée', null=True, verbose_name='Prochaine échéance de date')),
                ('alerte_km', models.PositiveIntegerField(blank=True, help_text="Marge d'alerte en kilomètres avant l'échéance", null=True, verbose_name="Marge d'alerte kilométrique")),
                ('alerte_mois', models.PositiveIntegerField(blank=True, help_text="Marge d'alerte en mois avant l'échéance", null=True, verbose_name="Marge d'alerte en mois")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='core.service', verbose_name='Service')),
                ('type_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='core.typemaintenance', verbose_name='Type de maintenance')),
                ('utilisateur', models.ForeignKey(limit_choices_to={'groupe__nom_groupe': 'Driver Principal'}, on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planifications', to='core.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Planification de maintenance',
                'verbose_name_plural': 'Planifications de maintenance',
                'ordering': ['prochaine_echeance_km'],
            },
        ),
    ]
