# Generated by Django 5.0.2 on 2025-04-15 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_planification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCourse',
            fields=[
                ('id_demande_course', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('lieu_depart', models.CharField(max_length=255)),
                ('lieu_arrivee', models.CharField(max_length=255)),
                ('date_heure_prevue', models.DateTimeField()),
                ('date_heure_fin_retour', models.DateTimeField()),
                ('objet', models.TextField()),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('affectée', 'Affectée'), ('rejetée', 'Rejetée')], default='en attente', max_length=20)),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
