# Generated by Django 5.0.2 on 2025-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_demandecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecourse',
            name='justification_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandecourse',
            name='statut',
            field=models.CharField(choices=[('soumise', 'Soumise'), ('rejetée', 'Rejetée'), ('acceptée', 'Acceptée'), ('planifiée', 'Planifiée'), ('terminée', 'Terminée')], default='soumise', max_length=20),
        ),
    ]
