# Generated by Django 5.0.2 on 2025-04-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_demandecourse_justification_rejet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecourse',
            name='id_vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicule'),
        ),
    ]
