# Generated by Django 5.0.2 on 2025-04-16 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_demandecourse_id_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecourse',
            name='id_auteur',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_auteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandecourse',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
