# Generated by Django 5.0.2 on 2025-04-17 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_demandecourse_id_auteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecourse',
            name='id_auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_auteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlanificationCourse',
            fields=[
                ('id_planification', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifiée', 'Planifiée'), ('terminée', 'Terminée')], default='planifiée', max_length=20)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.demandecourse')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
        ),
    ]
