# Generated by Django 5.2 on 2025-04-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_demandecourse_id_auteur_planificationcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificationcourse',
            name='lieu_arrivee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Lieu d'arrivée"),
        ),
    ]
