# Generated by Django 5.2 on 2025-04-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_planificationcourse_lieu_arrivee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificationcourse',
            name='demande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.demandecourse'),
        ),
        migrations.CreateModel(
            name='ExecutionCourse',
            fields=[
                ('id_execution', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_heure_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('kilometrage_debut', models.PositiveIntegerField(verbose_name='Kilométrage début')),
                ('kilometrage_fin', models.PositiveIntegerField(verbose_name='Kilométrage fin')),
                ('remarques_chauffeur', models.TextField(blank=True, null=True, verbose_name='Remarques du chauffeur')),
                ('id_planification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.planificationcourse')),
            ],
            options={
                'verbose_name': 'Exécution de Course',
                'verbose_name_plural': 'Exécutions de Course',
            },
        ),
    ]
