# Generated by Django 5.0 on 2026-04-27 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_planificationcourse_demande_executioncourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En service', 'En service'), ('En maintenance', 'En maintenance'), ('Non Disponible', 'Non Disponible'), ('Réformé', 'Réformé')], default='Disponible', max_length=15, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='VehiculeAffectation',
            fields=[
                ('id_affectation', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_vehicules', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur principal')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_creees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_vehicules', to='core.service')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.vehicule')),
            ],
            options={
                'verbose_name': 'Affectation véhicule',
                'verbose_name_plural': 'Affectations véhicules',
                'ordering': ['-date_debut', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='VehiculeDocument',
            fields=[
                ('id_document_vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('assurance', 'Assurance'), ('visite_technique', 'Visite technique'), ('carte_grise', 'Carte grise'), ('autre', 'Autre')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='vehicules/conformite/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.vehicule')),
            ],
            options={
                'verbose_name': 'Document véhicule',
                'verbose_name_plural': 'Documents véhicules',
                'ordering': ['date_expiration', '-date_creation'],
            },
        ),
    ]
