# Generated by Django 5.0 on 2026-04-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_vehicule_statut_vehiculeaffectation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte_carburant',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Attribué', 'Attribué'), ('Non disponible', 'Non disponible'), ('Bloquée', 'Bloquée')], default='Disponible', max_length=15, verbose_name='Statut'),
        ),
    ]
